//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILR1819.DataStore.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileDetail
    {
        public long ID { get; set; }
        public int UKPRN { get; set; }
        public string Filename { get; set; }
        public Nullable<long> FileSizeKb { get; set; }
        public Nullable<int> TotalLearnersSubmitted { get; set; }
        public Nullable<int> TotalValidLearnersSubmitted { get; set; }
        public Nullable<int> TotalInvalidLearnersSubmitted { get; set; }
        public Nullable<int> TotalErrorCount { get; set; }
        public Nullable<int> TotalWarningCount { get; set; }
        public Nullable<System.DateTime> SubmittedTime { get; set; }
        public Nullable<bool> Success { get; set; }
    }
}
