using ESFA.DC.ILR.FundingService.FM35.FundingOutput.Model.Attribute;
using ESFA.DC.ILR1819.DataStore.EF;

namespace ESFA.DC.ILR1819.DataStore.PersistData.Builders
{
    public class FM35LearningDeliveryBuilder
    {
        public static FM35_LearningDelivery BuildLearningDelivery(int ukPrn, string learnerRefNum, LearningDeliveryAttribute attribute)
        {
            return new FM35_LearningDelivery
            {
                UKPRN = ukPrn,
                LearnRefNumber = learnerRefNum,
                AimSeqNumber = attribute.AimSeqNumber ?? 0,
                AchApplicDate = attribute.LearningDeliveryAttributeDatas.AchApplicDate,
                Achieved = attribute.LearningDeliveryAttributeDatas.Achieved,
                AchieveElement = attribute.LearningDeliveryAttributeDatas.AchieveElement,
                AchievePayElig = attribute.LearningDeliveryAttributeDatas.AchievePayElig,
                AchievePayPctPreTrans = attribute.LearningDeliveryAttributeDatas.AchievePayPctPreTrans,
                AchPayTransHeldBack = attribute.LearningDeliveryAttributeDatas.AchPayTransHeldBack,
                ActualDaysIL = attribute.LearningDeliveryAttributeDatas.ActualDaysIL,
                ActualNumInstalm = attribute.LearningDeliveryAttributeDatas.ActualNumInstalm,
                ActualNumInstalmPreTrans = attribute.LearningDeliveryAttributeDatas.ActualNumInstalmPreTrans,
                ActualNumInstalmTrans = attribute.LearningDeliveryAttributeDatas.ActualNumInstalmTrans,
                AdjLearnStartDate = attribute.LearningDeliveryAttributeDatas.AdjLearnStartDate,
                AdltLearnResp = attribute.LearningDeliveryAttributeDatas.AdltLearnResp,
                AgeAimStart = attribute.LearningDeliveryAttributeDatas.AgeAimStart,
                AimValue = attribute.LearningDeliveryAttributeDatas.AimValue,
                AppAdjLearnStartDate = attribute.LearningDeliveryAttributeDatas.AppAdjLearnStartDate,
                AppAgeFact = attribute.LearningDeliveryAttributeDatas.AppAgeFact,
                AppATAGTA = attribute.LearningDeliveryAttributeDatas.AppATAGTA,
                AppCompetency = attribute.LearningDeliveryAttributeDatas.AppCompetency,
                AppFuncSkill = attribute.LearningDeliveryAttributeDatas.AppFuncSkill,
                AppFuncSkill1618AdjFact = attribute.LearningDeliveryAttributeDatas.AppFuncSkill1618AdjFact,
                AppKnowl = attribute.LearningDeliveryAttributeDatas.AppKnowl,
                AppLearnStartDate = attribute.LearningDeliveryAttributeDatas.AppLearnStartDate,
                ApplicEmpFactDate = attribute.LearningDeliveryAttributeDatas.ApplicEmpFactDate,
                ApplicFactDate = attribute.LearningDeliveryAttributeDatas.ApplicFactDate,
                ApplicFundRateDate = attribute.LearningDeliveryAttributeDatas.ApplicFundRateDate,
                ApplicProgWeightFact = attribute.LearningDeliveryAttributeDatas.ApplicProgWeightFact,
                ApplicUnweightFundRate = attribute.LearningDeliveryAttributeDatas.ApplicUnweightFundRate,
                ApplicWeightFundRate = attribute.LearningDeliveryAttributeDatas.ApplicWeightFundRate,
                AppNonFund = attribute.LearningDeliveryAttributeDatas.AppNonFund,
                AreaCostFactAdj = attribute.LearningDeliveryAttributeDatas.AreaCostFactAdj,
                BalInstalmPreTrans = attribute.LearningDeliveryAttributeDatas.BalInstalmPreTrans,
                BaseValueUnweight = attribute.LearningDeliveryAttributeDatas.BaseValueUnweight,
                CapFactor = attribute.LearningDeliveryAttributeDatas.CapFactor,
                DisUpFactAdj = attribute.LearningDeliveryAttributeDatas.DisUpFactAdj,
                EmpOutcomePayElig = attribute.LearningDeliveryAttributeDatas.EmpOutcomePayElig,
                EmpOutcomePctHeldBackTrans = attribute.LearningDeliveryAttributeDatas.EmpOutcomePctHeldBackTrans,
                EmpOutcomePctPreTrans = attribute.LearningDeliveryAttributeDatas.EmpOutcomePctPreTrans,
                EmpRespOth = attribute.LearningDeliveryAttributeDatas.EmpRespOth,
                ESOL = attribute.LearningDeliveryAttributeDatas.ESOL,
                FullyFund = attribute.LearningDeliveryAttributeDatas.FullyFund,
                FundLine = attribute.LearningDeliveryAttributeDatas.FundLine,
                FundStart = attribute.LearningDeliveryAttributeDatas.FundStart,
                LargeEmployerID = attribute.LearningDeliveryAttributeDatas.LargeEmployerID,
                LargeEmployerFM35Fctr = attribute.LearningDeliveryAttributeDatas.LargeEmployerFM35Fctr,
                LargeEmployerStatusDate = attribute.LearningDeliveryAttributeDatas.LargeEmployerStatusDate,
                LTRCUpliftFctr = attribute.LearningDeliveryAttributeDatas.LTRCUpliftFctr,
                NonGovCont = attribute.LearningDeliveryAttributeDatas.NonGovCont,
                OLASSCustody = attribute.LearningDeliveryAttributeDatas.OLASSCustody,
                OnProgPayPctPreTrans = attribute.LearningDeliveryAttributeDatas.OnProgPayPctPreTrans,
                OutstndNumOnProgInstalm = attribute.LearningDeliveryAttributeDatas.OutstndNumOnProgInstalm,
                OutstndNumOnProgInstalmTrans = attribute.LearningDeliveryAttributeDatas.OutstndNumOnProgInstalmTrans,
                PlannedNumOnProgInstalm = attribute.LearningDeliveryAttributeDatas.PlannedNumOnProgInstalm,
                PlannedNumOnProgInstalmTrans = attribute.LearningDeliveryAttributeDatas.PlannedNumOnProgInstalmTrans,
                PlannedTotalDaysIL = attribute.LearningDeliveryAttributeDatas.PlannedTotalDaysIL,
                PlannedTotalDaysILPreTrans = attribute.LearningDeliveryAttributeDatas.PlannedTotalDaysILPreTrans,
                PropFundRemain = attribute.LearningDeliveryAttributeDatas.PropFundRemain,
                PropFundRemainAch = attribute.LearningDeliveryAttributeDatas.PropFundRemainAch,
                PrscHEAim = attribute.LearningDeliveryAttributeDatas.PrscHEAim,
                Residential = attribute.LearningDeliveryAttributeDatas.Residential,
                Restart = attribute.LearningDeliveryAttributeDatas.Restart,
                SpecResUplift = attribute.LearningDeliveryAttributeDatas.SpecResUplift,
                StartPropTrans = attribute.LearningDeliveryAttributeDatas.StartPropTrans,
                ThresholdDays = attribute.LearningDeliveryAttributeDatas.ThresholdDays,
                Traineeship = attribute.LearningDeliveryAttributeDatas.Traineeship,
                Trans = attribute.LearningDeliveryAttributeDatas.Trans,
                TrnAdjLearnStartDate = attribute.LearningDeliveryAttributeDatas.TrnAdjLearnStartDate,
                TrnWorkPlaceAim = attribute.LearningDeliveryAttributeDatas.TrnWorkPlaceAim,
                TrnWorkPrepAim = attribute.LearningDeliveryAttributeDatas.TrnWorkPrepAim,
                UnWeightedRateFromESOL = attribute.LearningDeliveryAttributeDatas.UnWeightedRateFromESOL,
                UnweightedRateFromLARS = attribute.LearningDeliveryAttributeDatas.UnweightedRateFromLARS,
                WeightedRateFromESOL = attribute.LearningDeliveryAttributeDatas.WeightedRateFromESOL,
                WeightedRateFromLARS = attribute.LearningDeliveryAttributeDatas.WeightedRateFromLARS
            };
        }
    }
}
