queue:
  name: DCT
  demands: 
  - IsBuildServer
  - msbuild
  - Cmd
  - vstest

#Your build pipeline references the ‘BuildPlatform’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘BuildPlatform’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references an undefined variable named ‘$(Build.DefinitionName’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references the ‘BuildPlatform’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971


#Your build pipeline references the 'AppEarnHistory' variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the 'AppEarnTestConnectionString' variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the 'ArtifactFolderName' variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the 'BuildConfiguration' variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the 'BuildPlatform' variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the 'DatabaseProjectName' variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the 'Fm36HistoryTestConnectionString' variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the 'ILR1819DataStoreEntities' variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the 'ILR1819DataStoreEntitiesInvalid' variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the 'ILR1819DataStoreEntitiesValid' variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the 'IlrTestConnectionString' variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the 'PrivateSettingsCheckerURL' variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the 'ServiceFabricProjectFolderName' variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the 'ServiceFabricProjectLocation' variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the 'sfprojFileLocation' variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the 'SQLSERVER' variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the 'Target_Database_AppEarn' variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the 'UnitTestDbName' variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the 'VersionNumberMajor' variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the 'VersionNumberMinor' variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971


variables:
  PrivateSettingsCheckerURL: 'https://raw.githubusercontent.com/SkillsFundingAgency/DC-Tools/master/Scripts/PrivateSettingsChecker.ps1'
steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet <=4.8.0'
  inputs:
    versionSpec: '<=4.8.0'

    checkLatest: true


- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    vstsFeed: '1d5deb2d-cf8b-4bb1-b147-d13bc246e3f4'


- powershell: |
   $WebClient = New-Object System.Net.WebClient
   $WebClient.DownloadFile("$(PrivateSettingsCheckerURL)","$env:BUILD_REPOSITORY_LOCALPATH\src\PrivateSettingsChecker.ps1")
   write-host "download finished"
   
  displayName: 'Download script from DC-Tools - Private Settings Checker '

- task: PowerShell@2
  displayName: 'PowerShell Script'
  inputs:
    targetType: ./

    filePath: 'src\PrivateSettingsChecker.ps1'


- powershell: |
   Copy-Item "Cloud.xml" "Local.1Node.xml" -Force
   Copy-Item "Cloud.xml" "Local.5Node.xml" -Force
   
    
  workingDirectory: '$(System.DefaultWorkingDirectory)/src/ESFA.DC.ILR1819.DataStore/ApplicationParameters'

  displayName: 'Generate Fake Config Files'
  enabled: false

- task: MSBuild@1
  displayName: 'Build solution **/*.sln'
  inputs:
    msbuildArchitecture: x64

    platform: '$(BuildPlatform)'

    configuration: '$(BuildConfiguration)'

    msbuildArguments: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\applicationpackage" /p:version=$(Build.BuildNumber) /p:FileVersion=$(Build.BuildNumber)'

    clean: true

    maximumCpuCount: true

    logProjectEvents: true

    createLogFile: true


- task: CopyFiles@2
  displayName: 'Copy Files to: Acceptance Tests to Artifact Folder'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/src/'

    Contents: '**\*AcceptanceTests\bin\$(BuildConfiguration)\*.*'

    TargetFolder: '$(build.artifactstagingdirectory)\AcceptanceTests'

    CleanTargetFolder: true

    flattenFolders: true


- task: MSBuild@1
  displayName: 'Build solution - Service Fabric Project'
  inputs:
    solution: '$(ServiceFabricProjectLocation)\$(sfprojFileLocation)'

    msbuildArchitecture: x64

    platform: '$(BuildPlatform)'

    configuration: '$(BuildConfiguration)'

    msbuildArguments: '/p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /t:Package /p:PackageLocation="$(build.artifactstagingdirectory)\$(ArtifactFolderName)\ApplicationPackage" /p:version=$(Build.BuildNumber) /p:FileVersion=$(Build.BuildNumber)'

    maximumCpuCount: true

    logProjectEvents: true

    createLogFile: true


- task: DeleteFiles@1
  displayName: 'Delete Symbols files from Artifact Folder'
  inputs:
    SourceFolder: '$(build.artifactstagingdirectory)\$(ArtifactFolderName)\ApplicationPackage\'

    Contents: '**\*ApplicationPackage*\*.pdb'


- task: ServiceFabricUpdateManifests@2
  displayName: 'Update Service Fabric Manifests (Manifest versions)'
  inputs:
    applicationPackagePath: '$(build.artifactstagingdirectory)\$(ArtifactFolderName)\ApplicationPackage'

    versionBehavior: Replace


- task: CopyFiles@2
  displayName: 'Copy Nuget Package Files to: Artifact Nuget Directory'
  inputs:
    SourceFolder: '$(build.sourcesdirectory)\src'

    Contents: |
     **\*.nupkg
     !**\packages\**
     !**\bin\x64\**

    TargetFolder: '$(build.artifactstagingdirectory)\NugetPackages'

    flattenFolders: true


- task: CopyFiles@2
  displayName: 'Copy Database Files to: Artifact Databases Directory'
  inputs:
    SourceFolder: '$(ServiceFabricProjectLocation)'

    Contents: '**\*.dacpac'

    TargetFolder: '$(build.artifactstagingdirectory)\Databases'

    flattenFolders: true


- task: CopyFiles@2
  displayName: 'Copy ApplicationParameters Files to: Artifact ApplicationParameters Directory'
  inputs:
    SourceFolder: '$(ServiceFabricProjectLocation)\ApplicationParameters'

    Contents: '*.xml'

    TargetFolder: '$(build.artifactstagingdirectory)\$(ArtifactFolderName)\ApplicationParameters'

    CleanTargetFolder: true

    flattenFolders: true


- task: CopyFiles@2
  displayName: 'Copy PublishProfiles Files to: Artifact PublishProfiles Directory'
  inputs:
    SourceFolder: '$(ServiceFabricProjectLocation)'

    Contents: '**\PublishProfiles\*.xml'

    TargetFolder: '$(build.artifactstagingdirectory)\$(ArtifactFolderName)\PublishProfiles '

    CleanTargetFolder: true

    flattenFolders: true


- task: TotalALM.totalalm-tokenization.tokenization-build-task.Tokenization@2
  displayName: 'Tokenization: Transform file *Test.dll.config'
  inputs:
    SourcePath: '$(build.sourcesdirectory)\src'

    TargetFileNames: '*Test.dll.config'

    RequireVariable: true


- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     **\*test*.dll
     !**\*TestAdapter.dll
     !**\*AcceptanceTests.dll
     !**\obj\**

    runInParallel: false

    codeCoverageEnabled: true

    testRunTitle: '$($(Build.DefinitionName)'

    platform: '$(BuildPlatform)'

    configuration: '$(BuildConfiguration)'


- task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@5
  displayName: 'Check build quality'


- task: richardfennellBM.BM-VSTS-GenerateReleaseNotes-Task.Generate-Release-Notes.GenerateReleaseNotes@2
  displayName: 'Generate release notes'
  inputs:
    outputfile: '$(build.artifactstagingdirectory)\ReleaseNote.md'

    templateLocation: InLine

    inlinetemplate: |
     # Release notes for build $defname  
     **build**: $($build)   
     
     
     ***Note** that if the is a single associated item then then size is empty, but the item is returned  
     If there are multiple associated items then the size is >0  but you need to use an index to see each item*   
     **workitems:** [Size $($workitems.length)] $($workitems)     
     **workitems:** [Size $($workitems.length)] $($workitems[0])     
     
     **changesets:**[Size $($changesets.length)] $($changesets)     
     **changesets:**[Size $($changesets.length)] $($changesets[0])  
       
     ## Associated work items (Dump of all fields)  
     @@WILOOP@@  
     * **widetail:** $($widetail)
     * **widetail.fields:** $($widetail.fields)  
     * **widetail.links:** $($widetail.fields)  
     @@WILOOP@@  
       
     ## Associated change sets/commits (Dump of all fields) 
     @@CSLOOP@@  
     * **csdetail:** $($csdetail)    
     @@CSLOOP@@  

    generateForCurrentRelease: false

    maxWi: 75

    maxChanges: 75

  enabled: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

