CREATE TABLE [Rulebase].[AEC_HistoricEarningOutput] (
    [UKPRN]                                         INT             NOT NULL,
    [LearnRefNumber]                                VARCHAR (12)    NOT NULL,
    [AppIdentifierOutput]                           VARCHAR (10)    NOT NULL,
    [AppProgCompletedInTheYearOutput]               BIT             NULL,
    [HistoricDaysInYearOutput]                      INT             NULL,
    [HistoricEffectiveTNPStartDateOutput]           DATE            NULL,
    [HistoricEmpIdEndWithinYearOutput]              INT             NULL,
    [HistoricEmpIdStartWithinYearOutput]            INT             NULL,
    [HistoricFworkCodeOutput]                       INT             NULL,
    [HistoricLearner1618AtStartOutput]              BIT             NULL,
    [HistoricPMRAmountOutput]                       DECIMAL (12, 5) NULL,
    [HistoricProgrammeStartDateIgnorePathwayOutput] DATE            NULL,
    [HistoricProgrammeStartDateMatchPathwayOutput]  DATE            NULL,
    [HistoricProgTypeOutput]                        INT             NULL,
    [HistoricPwayCodeOutput]                        INT             NULL,
    [HistoricSTDCodeOutput]                         INT             NULL,
    [HistoricTNP1Output]                            DECIMAL (12, 5) NULL,
    [HistoricTNP2Output]                            DECIMAL (12, 5) NULL,
    [HistoricTNP3Output]                            DECIMAL (12, 5) NULL,
    [HistoricTNP4Output]                            DECIMAL (12, 5) NULL,
    [HistoricTotal1618UpliftPaymentsInTheYear]      DECIMAL (12, 5) NULL,
    [HistoricTotalProgAimPaymentsInTheYear]         DECIMAL (12, 5) NULL,
    [HistoricULNOutput]                             BIGINT          NULL,
    [HistoricUptoEndDateOutput]                     DATE            NULL,
    [HistoricVirtualTNP3EndofThisYearOutput]        DECIMAL (12, 5) NULL,
    [HistoricVirtualTNP4EndofThisYearOutput]        DECIMAL (12, 5) NULL,
    [HistoricLearnDelProgEarliestACT2DateOutput]    DATE            NULL,
    PRIMARY KEY CLUSTERED ([UKPRN] ASC, [LearnRefNumber] ASC, [AppIdentifierOutput] ASC)
);

