CREATE TABLE [Rulebase].[DV_Learner] (
    [UKPRN]                      INT            NOT NULL,
    [LearnRefNumber]             VARCHAR (12)   NOT NULL,
    [Learn_3rdSector]            INT            NULL,
    [Learn_Active]               INT            NULL,
    [Learn_ActiveJan]            INT            NULL,
    [Learn_ActiveNov]            INT            NULL,
    [Learn_ActiveOct]            INT            NULL,
    [Learn_Age31Aug]             INT            NULL,
    [Learn_BasicSkill]           INT            NULL,
    [Learn_EmpStatFDL]           INT            NULL,
    [Learn_EmpStatPrior]         INT            NULL,
    [Learn_FirstFullLevel2]      INT            NULL,
    [Learn_FirstFullLevel2Ach]   INT            NULL,
    [Learn_FirstFullLevel3]      INT            NULL,
    [Learn_FirstFullLevel3Ach]   INT            NULL,
    [Learn_FullLevel2]           INT            NULL,
    [Learn_FullLevel2Ach]        INT            NULL,
    [Learn_FullLevel3]           INT            NULL,
    [Learn_FullLevel3Ach]        INT            NULL,
    [Learn_FundAgency]           INT            NULL,
    [Learn_FundingSource]        INT            NULL,
    [Learn_FundPrvYr]            INT            NULL,
    [Learn_ILAcMonth1]           INT            NULL,
    [Learn_ILAcMonth10]          INT            NULL,
    [Learn_ILAcMonth11]          INT            NULL,
    [Learn_ILAcMonth12]          INT            NULL,
    [Learn_ILAcMonth2]           INT            NULL,
    [Learn_ILAcMonth3]           INT            NULL,
    [Learn_ILAcMonth4]           INT            NULL,
    [Learn_ILAcMonth5]           INT            NULL,
    [Learn_ILAcMonth6]           INT            NULL,
    [Learn_ILAcMonth7]           INT            NULL,
    [Learn_ILAcMonth8]           INT            NULL,
    [Learn_ILAcMonth9]           INT            NULL,
    [Learn_ILCurrAcYr]           INT            NULL,
    [Learn_LargeEmployer]        INT            NULL,
    [Learn_LenEmp]               INT            NULL,
    [Learn_LenUnemp]             INT            NULL,
    [Learn_LrnAimRecords]        INT            NULL,
    [Learn_ModeAttPlanHrs]       INT            NULL,
    [Learn_NotionLev]            INT            NULL,
    [Learn_NotionLevV2]          INT            NULL,
    [Learn_OLASS]                INT            NULL,
    [Learn_PrefMethContact]      INT            NULL,
    [Learn_PrimaryLLDD]          INT            NULL,
    [Learn_PriorEducationStatus] INT            NULL,
    [Learn_UnempBenFDL]          INT            NULL,
    [Learn_UnempBenPrior]        INT            NULL,
    [Learn_Uplift1516EFA]        DECIMAL (6, 5) NULL,
    [Learn_Uplift1516SFA]        DECIMAL (6, 5) NULL,
    PRIMARY KEY CLUSTERED ([UKPRN] ASC, [LearnRefNumber] ASC)
);
GO

ALTER TABLE [Rulebase].[DV_Learner] ADD CONSTRAINT [FK_DVLearner_DVglobal] FOREIGN KEY([UKPRN])
REFERENCES [Rulebase].[DV_global] ([UKPRN]);
GO

ALTER TABLE [Rulebase].[DV_Learner] CHECK CONSTRAINT [FK_DVLearner_DVglobal]
GO