CREATE TABLE [Rulebase].[DV_LearningDelivery] (
    [UKPRN]                                 INT            NOT NULL,
    [LearnRefNumber]                        VARCHAR (12)   NOT NULL,
    [AimSeqNumber]                          INT            NOT NULL,
    [LearnDel_AccToApp]                     INT            NULL,
    [LearnDel_AccToAppEmpDate]              DATE           NULL,
    [LearnDel_AccToAppEmpStat]              INT            NULL,
    [LearnDel_AchFullLevel2Pct]             DECIMAL (5, 2) NULL,
    [LearnDel_AchFullLevel3Pct]             DECIMAL (5, 2) NULL,
    [LearnDel_Achieved]                     INT            NULL,
    [LearnDel_AchievedIY]                   INT            NULL,
    [LearnDel_AcMonthYTD]                   VARCHAR (2)    NULL,
    [LearnDel_ActDaysILAfterCurrAcYr]       INT            NULL,
    [LearnDel_ActDaysILCurrAcYr]            INT            NULL,
    [LearnDel_ActEndDateOnAfterJan1]        INT            NULL,
    [LearnDel_ActEndDateOnAfterNov1]        INT            NULL,
    [LearnDel_ActEndDateOnAfterOct1]        INT            NULL,
    [LearnDel_ActiveIY]                     INT            NULL,
    [LearnDel_ActiveJan]                    INT            NULL,
    [LearnDel_ActiveNov]                    INT            NULL,
    [LearnDel_ActiveOct]                    INT            NULL,
    [LearnDel_ActTotalDaysIL]               INT            NULL,
    [LearnDel_AdvLoan]                      INT            NULL,
    [LearnDel_AgeAimOrigStart]              INT            NULL,
    [LearnDel_AgeAtStart]                   INT            NULL,
    [LearnDel_App]                          INT            NULL,
    [LearnDel_App1618Fund]                  INT            NULL,
    [LearnDel_App1925Fund]                  INT            NULL,
    [LearnDel_AppAimType]                   INT            NULL,
    [LearnDel_AppKnowl]                     INT            NULL,
    [LearnDel_AppMainAim]                   INT            NULL,
    [LearnDel_AppNonFund]                   INT            NULL,
    [LearnDel_BasicSkills]                  INT            NULL,
    [LearnDel_BasicSkillsParticipation]     INT            NULL,
    [LearnDel_BasicSkillsType]              INT            NULL,
    [LearnDel_CarryIn]                      INT            NULL,
    [LearnDel_ClassRm]                      INT            NULL,
    [LearnDel_CompAimApp]                   INT            NULL,
    [LearnDel_CompAimProg]                  INT            NULL,
    [LearnDel_Completed]                    INT            NULL,
    [LearnDel_CompletedIY]                  INT            NULL,
    [LearnDel_CompleteFullLevel2Pct]        DECIMAL (5, 2) NULL,
    [LearnDel_CompleteFullLevel3Pct]        DECIMAL (5, 2) NULL,
    [LearnDel_EFACoreAim]                   INT            NULL,
    [LearnDel_Emp6MonthAimStart]            INT            NULL,
    [LearnDel_Emp6MonthProgStart]           INT            NULL,
    [LearnDel_EmpDateBeforeFDL]             DATE           NULL,
    [LearnDel_EmpDatePriorFDL]              DATE           NULL,
    [LearnDel_EmpID]                        INT            NULL,
    [LearnDel_Employed]                     INT            NULL,
    [LearnDel_EmpStatFDL]                   INT            NULL,
    [LearnDel_EmpStatPrior]                 INT            NULL,
    [LearnDel_EmpStatPriorFDL]              INT            NULL,
    [LearnDel_EnhanAppFund]                 INT            NULL,
    [LearnDel_FullLevel2AchPct]             DECIMAL (5, 2) NULL,
    [LearnDel_FullLevel2ContPct]            DECIMAL (5, 2) NULL,
    [LearnDel_FullLevel3AchPct]             DECIMAL (5, 2) NULL,
    [LearnDel_FullLevel3ContPct]            DECIMAL (5, 2) NULL,
    [LearnDel_FuncSkills]                   INT            NULL,
    [LearnDel_FundAgency]                   INT            NULL,
    [LearnDel_FundingLineType]              VARCHAR (100)  NULL,
    [LearnDel_FundingSource]                INT            NULL,
    [LearnDel_FundPrvYr]                    INT            NULL,
    [LearnDel_FundStart]                    INT            NULL,
    [LearnDel_GCE]                          INT            NULL,
    [LearnDel_GCSE]                         INT            NULL,
    [LearnDel_ILAcMonth1]                   INT            NULL,
    [LearnDel_ILAcMonth10]                  INT            NULL,
    [LearnDel_ILAcMonth11]                  INT            NULL,
    [LearnDel_ILAcMonth12]                  INT            NULL,
    [LearnDel_ILAcMonth2]                   INT            NULL,
    [LearnDel_ILAcMonth3]                   INT            NULL,
    [LearnDel_ILAcMonth4]                   INT            NULL,
    [LearnDel_ILAcMonth5]                   INT            NULL,
    [LearnDel_ILAcMonth6]                   INT            NULL,
    [LearnDel_ILAcMonth7]                   INT            NULL,
    [LearnDel_ILAcMonth8]                   INT            NULL,
    [LearnDel_ILAcMonth9]                   INT            NULL,
    [LearnDel_ILCurrAcYr]                   INT            NULL,
    [LearnDel_IYActEndDate]                 DATE           NULL,
    [LearnDel_IYPlanEndDate]                DATE           NULL,
    [LearnDel_IYStartDate]                  DATE           NULL,
    [LearnDel_KeySkills]                    INT            NULL,
    [LearnDel_LargeEmpDiscountId]           INT            NULL,
    [LearnDel_LargeEmployer]                INT            NULL,
    [LearnDel_LastEmpDate]                  DATE           NULL,
    [LearnDel_LeaveMonth]                   INT            NULL,
    [LearnDel_LenEmp]                       INT            NULL,
    [LearnDel_LenUnemp]                     INT            NULL,
    [LearnDel_LoanBursFund]                 INT            NULL,
    [LearnDel_NotionLevel]                  INT            NULL,
    [LearnDel_NotionLevelV2]                INT            NULL,
    [LearnDel_NumHEDatasets]                INT            NULL,
    [LearnDel_OccupAim]                     INT            NULL,
    [LearnDel_OLASS]                        INT            NULL,
    [LearnDel_OLASSCom]                     INT            NULL,
    [LearnDel_OLASSCus]                     INT            NULL,
    [LearnDel_OrigStartDate]                DATE           NULL,
    [LearnDel_PlanDaysILAfterCurrAcYr]      INT            NULL,
    [LearnDel_PlanDaysILCurrAcYr]           INT            NULL,
    [LearnDel_PlanEndBeforeAug1]            INT            NULL,
    [LearnDel_PlanEndOnAfterJan1]           INT            NULL,
    [LearnDel_PlanEndOnAfterNov1]           INT            NULL,
    [LearnDel_PlanEndOnAfterOct1]           INT            NULL,
    [LearnDel_PlanTotalDaysIL]              INT            NULL,
    [LearnDel_PriorEducationStatus]         INT            NULL,
    [LearnDel_Prog]                         INT            NULL,
    [LearnDel_ProgAimAch]                   INT            NULL,
    [LearnDel_ProgAimApp]                   INT            NULL,
    [LearnDel_ProgCompleted]                INT            NULL,
    [LearnDel_ProgCompletedIY]              INT            NULL,
    [LearnDel_ProgStartDate]                DATE           NULL,
    [LearnDel_QCF]                          INT            NULL,
    [LearnDel_QCFCert]                      INT            NULL,
    [LearnDel_QCFDipl]                      INT            NULL,
    [LearnDel_QCFType]                      INT            NULL,
    [LearnDel_RegAim]                       INT            NULL,
    [LearnDel_SecSubAreaTier1]              VARCHAR (3)    NULL,
    [LearnDel_SecSubAreaTier2]              VARCHAR (5)    NULL,
    [LearnDel_SFAApproved]                  INT            NULL,
    [LearnDel_SourceFundEFA]                INT            NULL,
    [LearnDel_SourceFundSFA]                INT            NULL,
    [LearnDel_StartBeforeApr1]              INT            NULL,
    [LearnDel_StartBeforeAug1]              INT            NULL,
    [LearnDel_StartBeforeDec1]              INT            NULL,
    [LearnDel_StartBeforeFeb1]              INT            NULL,
    [LearnDel_StartBeforeJan1]              INT            NULL,
    [LearnDel_StartBeforeJun1]              INT            NULL,
    [LearnDel_StartBeforeMar1]              INT            NULL,
    [LearnDel_StartBeforeMay1]              INT            NULL,
    [LearnDel_StartBeforeNov1]              INT            NULL,
    [LearnDel_StartBeforeOct1]              INT            NULL,
    [LearnDel_StartBeforeSep1]              INT            NULL,
    [LearnDel_StartIY]                      INT            NULL,
    [LearnDel_StartJan1]                    INT            NULL,
    [LearnDel_StartMonth]                   INT            NULL,
    [LearnDel_StartNov1]                    INT            NULL,
    [LearnDel_StartOct1]                    INT            NULL,
    [LearnDel_SuccRateStat]                 INT            NULL,
    [LearnDel_TrainAimType]                 INT            NULL,
    [LearnDel_TransferDiffProvider]         INT            NULL,
    [LearnDel_TransferDiffProviderGovStrat] INT            NULL,
    [LearnDel_TransferProvider]             INT            NULL,
    [LearnDel_UfIProv]                      INT            NULL,
    [LearnDel_UnempBenFDL]                  INT            NULL,
    [LearnDel_UnempBenPrior]                INT            NULL,
    [LearnDel_Withdrawn]                    INT            NULL,
    [LearnDel_WorkplaceLocPostcode]         VARCHAR (8)    NULL,
    [Prog_AccToApp]                         INT            NULL,
    [Prog_Achieved]                         INT            NULL,
    [Prog_AchievedIY]                       INT            NULL,
    [Prog_ActEndDate]                       DATE           NULL,
    [Prog_ActiveIY]                         INT            NULL,
    [Prog_AgeAtStart]                       INT            NULL,
    [Prog_EarliestAim]                      INT            NULL,
    [Prog_Employed]                         INT            NULL,
    [Prog_FundPrvYr]                        INT            NULL,
    [Prog_ILCurrAcYear]                     INT            NULL,
    [Prog_LatestAim]                        INT            NULL,
    [Prog_SourceFundEFA]                    INT            NULL,
    [Prog_SourceFundSFA]                    INT            NULL,
    PRIMARY KEY CLUSTERED ([UKPRN] ASC, [LearnRefNumber] ASC, [AimSeqNumber] ASC)
);

