CREATE TABLE [Rulebase].[FM35_LearningDelivery] (
    [UKPRN]                        INT             NOT NULL,
    [LearnRefNumber]               VARCHAR (12)    NOT NULL,
    [AimSeqNumber]                 INT             NOT NULL,
    [AchApplicDate]                DATE            NULL,
    [Achieved]                     BIT             NULL,
    [AchieveElement]               DECIMAL (10, 5) NULL,
    [AchievePayElig]               BIT             NULL,
    [AchievePayPctPreTrans]        DECIMAL (10, 5) NULL,
    [AchPayTransHeldBack]          DECIMAL (10, 5) NULL,
    [ActualDaysIL]                 INT             NULL,
    [ActualNumInstalm]             INT             NULL,
    [ActualNumInstalmPreTrans]     INT             NULL,
    [ActualNumInstalmTrans]        INT             NULL,
    [AdjLearnStartDate]            DATE            NULL,
    [AdltLearnResp]                BIT             NULL,
    [AgeAimStart]                  INT             NULL,
    [AimValue]                     DECIMAL (10, 5) NULL,
    [AppAdjLearnStartDate]         DATE            NULL,
    [AppAgeFact]                   DECIMAL (10, 5) NULL,
    [AppATAGTA]                    BIT             NULL,
    [AppCompetency]                BIT             NULL,
    [AppFuncSkill]                 BIT             NULL,
    [AppFuncSkill1618AdjFact]      DECIMAL (10, 5) NULL,
    [AppKnowl]                     BIT             NULL,
    [AppLearnStartDate]            DATE            NULL,
    [ApplicEmpFactDate]            DATE            NULL,
    [ApplicFactDate]               DATE            NULL,
    [ApplicFundRateDate]           DATE            NULL,
    [ApplicProgWeightFact]         VARCHAR (1)     NULL,
    [ApplicUnweightFundRate]       DECIMAL (10, 5) NULL,
    [ApplicWeightFundRate]         DECIMAL (10, 5) NULL,
    [AppNonFund]                   BIT             NULL,
    [AreaCostFactAdj]              DECIMAL (10, 5) NULL,
    [BalInstalmPreTrans]           INT             NULL,
    [BaseValueUnweight]            DECIMAL (10, 5) NULL,
    [CapFactor]                    DECIMAL (10, 5) NULL,
    [DisUpFactAdj]                 DECIMAL (10, 4) NULL,
    [EmpOutcomePayElig]            BIT             NULL,
    [EmpOutcomePctHeldBackTrans]   DECIMAL (10, 5) NULL,
    [EmpOutcomePctPreTrans]        DECIMAL (10, 5) NULL,
    [EmpRespOth]                   BIT             NULL,
    [ESOL]                         BIT             NULL,
    [FullyFund]                    BIT             NULL,
    [FundLine]                     VARCHAR (100)   NULL,
    [FundStart]                    BIT             NULL,
    [LargeEmployerID]              INT             NULL,
    [LargeEmployerFM35Fctr]        DECIMAL (10, 2) NULL,
    [LargeEmployerStatusDate]      DATE            NULL,
    [LTRCUpliftFctr]               DECIMAL (10, 5) NULL,
    [NonGovCont]                   DECIMAL (10, 5) NULL,
    [OLASSCustody]                 BIT             NULL,
    [OnProgPayPctPreTrans]         DECIMAL (10, 5) NULL,
    [OutstndNumOnProgInstalm]      INT             NULL,
    [OutstndNumOnProgInstalmTrans] INT             NULL,
    [PlannedNumOnProgInstalm]      INT             NULL,
    [PlannedNumOnProgInstalmTrans] INT             NULL,
    [PlannedTotalDaysIL]           INT             NULL,
    [PlannedTotalDaysILPreTrans]   INT             NULL,
    [PropFundRemain]               DECIMAL (10, 2) NULL,
    [PropFundRemainAch]            DECIMAL (10, 2) NULL,
    [PrscHEAim]                    BIT             NULL,
    [Residential]                  BIT             NULL,
    [Restart]                      BIT             NULL,
    [SpecResUplift]                DECIMAL (10, 5) NULL,
    [StartPropTrans]               DECIMAL (10, 5) NULL,
    [ThresholdDays]                INT             NULL,
    [Traineeship]                  BIT             NULL,
    [Trans]                        BIT             NULL,
    [TrnAdjLearnStartDate]         DATE            NULL,
    [TrnWorkPlaceAim]              BIT             NULL,
    [TrnWorkPrepAim]               BIT             NULL,
    [UnWeightedRateFromESOL]       DECIMAL (10, 5) NULL,
    [UnweightedRateFromLARS]       DECIMAL (10, 5) NULL,
    [WeightedRateFromESOL]         DECIMAL (10, 5) NULL,
    [WeightedRateFromLARS]         DECIMAL (10, 5) NULL,
    CONSTRAINT [PK_FM35_LearningDelivery] PRIMARY KEY CLUSTERED ([UKPRN] ASC, [LearnRefNumber] ASC, [AimSeqNumber] ASC)
);

