CREATE TABLE [Rulebase].[TBL_LearningDelivery] (
    [UKPRN]                          INT             NOT NULL,
    [LearnRefNumber]                 VARCHAR (12)    NOT NULL,
    [AimSeqNumber]                   INT             NOT NULL,
    [ProgStandardStartDate]          DATE            NULL,
    [FundLine]                       VARCHAR (50)    NULL,
    [MathEngAimValue]                DECIMAL (10, 5) NULL,
    [PlannedNumOnProgInstalm]        INT             NULL,
    [LearnSuppFundCash]              DECIMAL (10, 5) NULL,
    [AdjProgStartDate]               DATE            NULL,
    [LearnSuppFund]                  BIT             NULL,
    [MathEngOnProgPayment]           DECIMAL (10, 5) NULL,
    [InstPerPeriod]                  INT             NULL,
    [SmallBusPayment]                DECIMAL (10, 5) NULL,
    [YoungAppSecondPayment]          DECIMAL (10, 5) NULL,
    [CoreGovContPayment]             DECIMAL (10, 5) NULL,
    [YoungAppEligible]               BIT             NULL,
    [SmallBusEligible]               BIT             NULL,
    [MathEngOnProgPct]               INT             NULL,
    [AgeStandardStart]               INT             NULL,
    [YoungAppSecondThresholdDate]    DATE            NULL,
    [EmpIdFirstDayStandard]          INT             NULL,
    [EmpIdFirstYoungAppDate]         INT             NULL,
    [EmpIdSecondYoungAppDate]        INT             NULL,
    [EmpIdSmallBusDate]              INT             NULL,
    [YoungAppFirstThresholdDate]     DATE            NULL,
    [AchApplicDate]                  DATE            NULL,
    [AchEligible]                    BIT             NULL,
    [Achieved]                       BIT             NULL,
    [AchievementApplicVal]           DECIMAL (10, 5) NULL,
    [AchPayment]                     DECIMAL (10, 5) NULL,
    [ActualNumInstalm]               INT             NULL,
    [CombinedAdjProp]                BIGINT          NULL,
    [EmpIdAchDate]                   INT             NULL,
    [LearnDelDaysIL]                 INT             NULL,
    [LearnDelStandardAccDaysIL]      INT             NULL,
    [LearnDelStandardPrevAccDaysIL]  INT             NULL,
    [LearnDelStandardTotalDaysIL]    INT             NULL,
    [ActualDaysIL]                   INT             NULL,
    [MathEngBalPayment]              DECIMAL (10, 5) NULL,
    [MathEngBalPct]                  BIGINT          NULL,
    [MathEngLSFFundStart]            BIT             NULL,
    [PlannedTotalDaysIL]             INT             NULL,
    [MathEngLSFThresholdDays]        INT             NULL,
    [OutstandNumOnProgInstalm]       INT             NULL,
    [SmallBusApplicVal]              DECIMAL (10, 5) NULL,
    [SmallBusStatusFirstDayStandard] INT             NULL,
    [SmallBusStatusThreshold]        INT             NULL,
    [YoungAppApplicVal]              DECIMAL (10, 5) NULL,
    [CoreGovContCapApplicVal]        BIGINT          NULL,
    [CoreGovContUncapped]            DECIMAL (10, 5) NULL,
    [ApplicFundValDate]              DATE            NULL,
    [YoungAppFirstPayment]           DECIMAL (10, 5) NULL,
    [YoungAppPayment]                DECIMAL (10, 5) NULL,
    PRIMARY KEY CLUSTERED ([UKPRN] ASC, [LearnRefNumber] ASC, [AimSeqNumber] ASC)
);

