//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILR1819.DataStore.EF.Valid
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningDeliveryHE
    {
        public int UKPRN { get; set; }
        public string LearnRefNumber { get; set; }
        public int AimSeqNumber { get; set; }
        public string NUMHUS { get; set; }
        public string SSN { get; set; }
        public string QUALENT3 { get; set; }
        public Nullable<int> SOC2000 { get; set; }
        public Nullable<int> SEC { get; set; }
        public string UCASAPPID { get; set; }
        public int TYPEYR { get; set; }
        public int MODESTUD { get; set; }
        public int FUNDLEV { get; set; }
        public int FUNDCOMP { get; set; }
        public Nullable<decimal> STULOAD { get; set; }
        public int YEARSTU { get; set; }
        public int MSTUFEE { get; set; }
        public Nullable<decimal> PCOLAB { get; set; }
        public Nullable<decimal> PCFLDCS { get; set; }
        public Nullable<decimal> PCSLDCS { get; set; }
        public Nullable<decimal> PCTLDCS { get; set; }
        public int SPECFEE { get; set; }
        public Nullable<int> NETFEE { get; set; }
        public Nullable<int> GROSSFEE { get; set; }
        public string DOMICILE { get; set; }
        public Nullable<int> ELQ { get; set; }
        public string HEPostCode { get; set; }
    }
}
