//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILR1819.DataStore.EF.Invalid
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningDeliveryHE
    {
        public int LearningDeliveryHE_Id { get; set; }
        public int UKPRN { get; set; }
        public Nullable<int> LearningDelivery_Id { get; set; }
        public string LearnRefNumber { get; set; }
        public Nullable<long> AimSeqNumber { get; set; }
        public string NUMHUS { get; set; }
        public string SSN { get; set; }
        public string QUALENT3 { get; set; }
        public Nullable<long> SOC2000 { get; set; }
        public Nullable<long> SEC { get; set; }
        public string UCASAPPID { get; set; }
        public Nullable<long> TYPEYR { get; set; }
        public Nullable<long> MODESTUD { get; set; }
        public Nullable<long> FUNDLEV { get; set; }
        public Nullable<long> FUNDCOMP { get; set; }
        public Nullable<double> STULOAD { get; set; }
        public Nullable<long> YEARSTU { get; set; }
        public Nullable<long> MSTUFEE { get; set; }
        public Nullable<double> PCOLAB { get; set; }
        public Nullable<double> PCFLDCS { get; set; }
        public Nullable<double> PCSLDCS { get; set; }
        public Nullable<double> PCTLDCS { get; set; }
        public Nullable<long> SPECFEE { get; set; }
        public Nullable<long> NETFEE { get; set; }
        public Nullable<long> GROSSFEE { get; set; }
        public string DOMICILE { get; set; }
        public Nullable<long> ELQ { get; set; }
        public string HEPostCode { get; set; }
    }
}
