//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILR1819.DataStore.EF.Invalid
{
    using System;
    using System.Collections.Generic;
    
    public partial class LLDDandHealthProblem
    {
        public int LLDDandHealthProblem_Id { get; set; }
        public Nullable<int> Learner_Id { get; set; }
        public int UKPRN { get; set; }
        public string LearnRefNumber { get; set; }
        public Nullable<long> LLDDCat { get; set; }
        public Nullable<long> PrimaryLLDD { get; set; }
    }
}
